services:
  storage:
    image: rustfs/rustfs:latest
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Console
    volumes:
      - rustfs-data:/data
    environment:
      - RUSTFS_ACCESS_KEY=rustfsadmin
      - RUSTFS_SECRET_KEY=rustfsadmin
    command: --address :9000 --access-key rustfsadmin --secret-key rustfsadmin /data
  postgres:
    image: postgres:18.4
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: bibliograph
      POSTGRES_PASSWORD: bibliograph
      POSTGRES_DB: bibliograph
volumes:
  rustfs-data:
  pgdata:
